name: Release

on:
    push:
        branches: [main, next]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: |
                  if [ ! -f package.json ]; then
                    echo '{"name": "project", "version": "1.0.0", "private": true}' > package.json
                  fi
                  npm install --no-audit --silent \
                    @semantic-release/commit-analyzer \
                    @semantic-release/release-notes-generator \
                    @semantic-release/github \
                    conventional-changelog-conventionalcommits
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Run semantic-release
              run: npx semantic-release --branches main,next --extends @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
